spring.application.name=SpringJDBCx
spring.datasource.url=jdbc:mysql://localhost:3306/bankmanagementsystem
spring.datasource.username=root
spring.datasource.password=Ninnu#1352
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver